In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\African_crises_dataset.csv")
df

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,0,0,0,crisis
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,0,0,0,no_crisis
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,0,0,0,no_crisis
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,0,0,0,no_crisis
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,0,0,0,no_crisis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,70,ZWE,Zimbabwe,2009,1,354.800000,1,1,0.0,-7.670000,1,1,0,crisis
1055,70,ZWE,Zimbabwe,2010,0,378.200000,1,1,0.0,3.217000,1,0,0,no_crisis
1056,70,ZWE,Zimbabwe,2011,0,361.900000,1,1,0.0,4.920000,1,0,0,no_crisis
1057,70,ZWE,Zimbabwe,2012,0,361.900000,1,1,0.0,3.720000,1,0,0,no_crisis
1058,70,ZWE,Zimbabwe,2013,0,361.900000,1,1,0.0,1.632000,1,0,0,no_crisis

In [3]:
df.describe()

,country_number,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises
count,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1.059000e+03,1059.000000,1059.000000,1059.000000
mean,35.613787,1967.767705,0.077432,43.140831,0.039660,0.152975,0.006402,2.084889e+04,0.776204,0.132200,0.129367
std,23.692402,33.530632,0.267401,111.475380,0.195251,0.360133,0.043572,6.757274e+05,0.416984,0.349847,0.335765
min,1.000000,1860.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.850214e+01,0.000000,0.000000,0.000000
25%,15.000000,1951.000000,0.000000,0.195350,0.000000,0.000000,0.000000,2.086162e+00,1.000000,0.000000,0.000000
50%,38.000000,1973.000000,0.000000,0.868400,0.000000,0.000000,0.000000,5.762330e+00,1.000000,0.000000,0.000000
75%,56.000000,1994.000000,0.000000,8.462750,0.000000,0.000000,0.000000,1.164405e+01,1.000000,0.000000,0.000000
max,70.000000,2014.000000,1.000000,744.306139,1.000000,1.000000,0.400000,2.198970e+07,1.000000,2.000000,1.000000

In [4]:
from sklearn.preprocessing import OneHotEncoder

# assume 'df' is your DataFrame and 'country' is the column you want to one hot encode
ohe = OneHotEncoder()
country_ohe = ohe.fit_transform(df[['country']])

# get the feature names from the categories_ attribute
feature_names = [f'country_{cat}' for cat in ohe.categories_[0]]

# convert the encoded data back into a DataFrame
country_ohe_df = pd.DataFrame(country_ohe.toarray(), columns=feature_names)

# concatenate the original DataFrame with the one hot encoded country data
df = pd.concat([df, country_ohe_df], axis=1)

In [5]:
df

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Egypt,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,70,ZWE,Zimbabwe,2009,1,354.800000,1,1,0.0,-7.670000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1055,70,ZWE,Zimbabwe,2010,0,378.200000,1,1,0.0,3.217000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1056,70,ZWE,Zimbabwe,2011,0,361.900000,1,1,0.0,4.920000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1057,70,ZWE,Zimbabwe,2012,0,361.900000,1,1,0.0,3.720000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1058,70,ZWE,Zimbabwe,2013,0,361.900000,1,1,0.0,1.632000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country_number                    1059 non-null   int64
 1   country_code                      1059 non-null   object
 2   country                           1059 non-null   object
 3   year                              1059 non-null   int64
 4   systemic_crisis                   1059 non-null   int64
 5   exch_usd                          1059 non-null   float64
 6   domestic_debt_in_default          1059 non-null   int64
 7   sovereign_external_debt_default   1059 non-null   int64
 8   gdp_weighted_default              1059 non-null   float64
 9   inflation_annual_cpi              1059 non-null   float64
 10  independence                      1059 non-null   int64
 11  currency_crises                   1059 non-null   int64
 12  inflation_crises                  1059 non-null   int64
 13  banking_crisis                    1059 non-null   object
 14  country_Algeria                   1059 non-null   float64
 15  country_Angola                    1059 non-null   float64
 16  country_Central African Republic  1059 non-null   float64
 17  country_Egypt                     1059 non-null   float64
 18  country_Ivory Coast               1059 non-null   float64
 19  country_Kenya                     1059 non-null   float64
 20  country_Mauritius                 1059 non-null   float64
 21  country_Morocco                   1059 non-null   float64
 22  country_Nigeria                   1059 non-null   float64
 23  country_South Africa              1059 non-null   float64
 24  country_Tunisia                   1059 non-null   float64
 25  country_Zambia                    1059 non-null   float64
 26  country_Zimbabwe                  1059 non-null   float64
dtypes: float64(16), int64(8), object(3)
memory usage: 223.5+ KB

In [7]:
df.head()

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Egypt,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
selected_features=['year','systemic_crisis','bank_crisis_encoded','exch_usd','domestic_debt_in_default','sovereign_external_debt_default','gdp_weighted_default','inflation_annual_cpi','independence','currency_crises','inflation_crises','country_Egypt','country_Ivory Coast','country_Kenya','country_Mauritius','country_Morocco','country_Nigeria','country_South Africa','country_Tunisia','country_Zambia','country_Zimbabwe']
correlation_matrix = df[selected_features].corr()
correlation_matrix

,year,systemic_crisis,bank_crisis_encoded,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,...,country_Egypt,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe
year,1.000000,0.197450,0.213774,0.248757,0.136828,0.271890,-0.054670,0.037035,0.407360,0.189390,...,-0.380137,0.114306,0.102608,0.099515,0.076051,0.117843,-0.116771,0.076051,0.086490,0.005750
systemic_crisis,0.197450,1.000000,0.853702,0.202687,0.122158,0.249850,0.005274,0.106452,0.147083,0.112751,...,-0.059990,-0.013117,0.113375,-0.075889,-0.052437,0.081822,-0.100623,-0.011119,-0.022106,0.101751
bank_crisis_encoded,0.213774,0.853702,1.000000,0.168775,0.225797,0.263992,0.026545,0.098860,0.159620,0.166859,...,-0.025909,-0.022348,0.027999,-0.068211,-0.060279,0.081492,-0.076264,-0.021450,-0.031536,0.083481
exch_usd,0.248757,0.202687,0.168775,1.000000,0.005253,0.422890,-0.040726,-0.011947,0.126034,-0.056472,...,-0.156584,0.248696,-0.028987,-0.069074,-0.092360,-0.009215,-0.129118,0.018712,-0.101868,-0.062726
domestic_debt_in_default,0.136828,0.122158,0.225797,0.005253,1.000000,0.464751,-0.029874,0.151832,0.109120,0.227585,...,-0.084148,-0.051110,-0.052814,-0.053233,-0.056104,-0.049803,-0.070583,-0.056104,-0.054887,0.458601
sovereign_external_debt_default,0.271890,0.249850,0.263992,0.422890,0.464751,1.000000,0.345919,0.072609,0.228192,0.199428,...,-0.131443,0.214737,-0.045789,-0.111321,-0.055969,-0.002025,-0.105284,-0.045743,0.010274,0.152700
gdp_weighted_default,-0.054670,0.005274,0.026545,-0.040726,-0.029874,0.345919,1.000000,-0.004535,0.078936,0.016970,...,0.086347,-0.036972,-0.038205,-0.038508,0.025342,-0.036027,0.074864,-0.005086,-0.039705,-0.044802
inflation_annual_cpi,0.037035,0.106452,0.098860,-0.011947,0.151832,0.072609,-0.004535,1.000000,0.016569,0.076590,...,-0.012779,-0.007761,-0.008019,-0.008083,-0.008519,-0.007560,-0.010719,-0.008518,-0.008328,0.101190
independence,0.407360,0.147083,0.159620,0.126034,0.109120,0.228192,0.078936,0.016569,1.000000,0.086376,...,0.222341,0.058419,-0.000053,-0.007227,0.006930,0.072792,0.113398,0.006930,-0.043982,-0.169466
currency_crises,0.189390,0.112751,0.166859,-0.056472,0.227585,0.199428,0.016970,0.076590,0.086376,1.000000,...,-0.095428,-0.083666,0.001582,-0.043951,-0.020159,0.024156,0.008096,0.000895,0.101714,0.088141
inflation_crises,0.098630,0.172562,0.235852,-0.063783,0.224429,0.187930,0.017630,0.080060,-0.022548,0.393376,...,-0.072055,-0.049367,-0.053948,-0.032105,0.003263,0.051579,-0.124807,-0.018674,0.119438,0.074231
country_Egypt,-0.380137,-0.059990,-0.025909,-0.156584,-0.084148,-0.131443,0.086347,-0.012779,0.222341,-0.095428,...,1.000000,-0.104141,-0.107613,-0.108467,-0.114318,-0.101479,-0.143820,-0.114318,-0.111838,-0.126195
country_Ivory Coast,0.114306,-0.013117,-0.022348,0.248696,-0.051110,0.214737,-0.036972,-0.007761,0.058419,-0.083666,...,-0.104141,1.000000,-0.065362,-0.065881,-0.069434,-0.061636,-0.087353,-0.069434,-0.067928,-0.076648
country_Kenya,0.102608,0.113375,0.027999,-0.028987,-0.052814,-0.045789,-0.038205,-0.008019,-0.000053,0.001582,...,-0.107613,-0.065362,1.000000,-0.068077,-0.071749,-0.063690,-0.090265,-0.071749,-0.070192,-0.079203
country_Mauritius,0.099515,-0.075889,-0.068211,-0.069074,-0.053233,-0.111321,-0.038508,-0.008083,-0.007227,-0.043951,...,-0.108467,-0.065881,-0.068077,1.000000,-0.072319,-0.064196,-0.090982,-0.072319,-0.070750,-0.079832
country_Morocco,0.076051,-0.052437,-0.060279,-0.092360,-0.056104,-0.055969,0.025342,-0.008519,0.006930,-0.020159,...,-0.114318,-0.069434,-0.071749,-0.072319,1.000000,-0.067659,-0.095889,-0.076220,-0.074566,-0.084138
country_Nigeria,0.117843,0.081822,0.081492,-0.009215,-0.049803,-0.002025,-0.036027,-0.007560,0.072792,0.024156,...,-0.101479,-0.061636,-0.063690,-0.064196,-0.067659,1.000000,-0.085120,-0.067659,-0.066191,-0.074688
country_South Africa,-0.116771,-0.100623,-0.076264,-0.129118,-0.070583,-0.105284,0.074864,-0.010719,0.113398,0.008096,...,-0.143820,-0.087353,-0.090265,-0.090982,-0.095889,-0.085120,1.000000,-0.095889,-0.093809,-0.105851
country_Tunisia,0.076051,-0.011119,-0.021450,0.018712,-0.056104,-0.045743,-0.005086,-0.008518,0.006930,0.000895,...,-0.114318,-0.069434,-0.071749,-0.072319,-0.076220,-0.067659,-0.095889,1.000000,-0.074566,-0.084138
country_Zambia,0.086490,-0.022106,-0.031536,-0.101868,-0.054887,0.010274,-0.039705,-0.008328,-0.043982,0.101714,...,-0.111838,-0.067928,-0.070192,-0.070750,-0.074566,-0.066191,-0.093809,-0.074566,1.000000,-0.082313
country_Zimbabwe,0.005750,0.101751,0.083481,-0.062726,0.458601,0.152700,-0.044802,0.101190,-0.169466,0.088141,...,-0.126195,-0.076648,-0.079203,-0.079832,-0.084138,-0.074688,-0.105851,-0.084138,-0.082313,1.000000

In [8]:
value_counts = df['banking_crisis'].value_counts()

print(value_counts)

banking_crisis
no_crisis    965
crisis        94
Name: count, dtype: int64

In [14]:
df

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Egypt,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,70,ZWE,Zimbabwe,2009,1,354.800000,1,1,0.0,-7.670000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1055,70,ZWE,Zimbabwe,2010,0,378.200000,1,1,0.0,3.217000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1056,70,ZWE,Zimbabwe,2011,0,361.900000,1,1,0.0,4.920000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1057,70,ZWE,Zimbabwe,2012,0,361.900000,1,1,0.0,3.720000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1058,70,ZWE,Zimbabwe,2013,0,361.900000,1,1,0.0,1.632000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
df.head()

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe,banking_crisis_encoded
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [9]:
# Manual mapping
crisis_mapping = {'crisis': 1, 'no_crisis': 0}
df['bank_crisis_encoded'] = df['banking_crisis'].map(crisis_mapping)

df.head()

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe,bank_crisis_encoded
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [21]:
df.head(50)

,country_number,country_code,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,...,country_Ivory Coast,country_Kenya,country_Mauritius,country_Morocco,country_Nigeria,country_South Africa,country_Tunisia,country_Zambia,country_Zimbabwe,banking_crisis_encoded
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
5,1,DZA,Algeria,1875,0,0.051546,0,0,0.0,-20.924178,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
6,1,DZA,Algeria,1876,0,0.051867,0,0,0.0,-1.769547,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
7,1,DZA,Algeria,1877,0,0.051867,0,0,0.0,29.116045,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
8,1,DZA,Algeria,1878,0,0.051948,0,0,0.0,-1.492537,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
9,1,DZA,Algeria,1879,0,0.052029,0,0,0.0,-16.831357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
10,1,DZA,Algeria,1880,0,0.052356,0,0,0.0,3.881188,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11,1,DZA,Algeria,1881,0,0.052029,0,0,0.0,12.619138,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
12,1,DZA,Algeria,1882,0,0.050761,0,0,0.0,-12.356127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
13,1,DZA,Algeria,1883,0,0.052002,0,0,0.0,-1.390498,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
14,1,DZA,Algeria,1884,0,0.052165,0,0,0.0,-15.942029,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
15,1,DZA,Algeria,1939,0,0.449030,0,0,0.0,9.756098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
16,1,DZA,Algeria,1940,0,0.491890,0,0,0.0,22.222222,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
17,1,DZA,Algeria,1941,0,0.449370,0,0,0.0,16.363636,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
18,1,DZA,Algeria,1942,0,0.750000,0,0,0.0,28.125000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
19,1,DZA,Algeria,1943,0,0.500000,0,0,0.0,46.341463,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
20,1,DZA,Algeria,1944,0,0.500000,0,0,0.0,41.666667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
21,1,DZA,Algeria,1945,0,1.191000,0,0,0.0,29.411765,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
22,1,DZA,Algeria,1946,0,1.191000,0,0,0.0,18.181818,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
23,1,DZA,Algeria,1947,0,1.193000,0,0,0.0,69.230769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
24,1,DZA,Algeria,1948,0,2.662000,0,0,0.0,63.636364,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
25,1,DZA,Algeria,1949,0,3.490000,0,0,0.0,23.611111,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
26,1,DZA,Algeria,1950,0,3.499000,0,0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
27,1,DZA,Algeria,1951,0,3.500000,0,0,0.0,6.741573,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
28,1,DZA,Algeria,1952,0,3.500000,0,0,0.0,6.315789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
29,1,DZA,Algeria,1953,0,3.500000,0,0,0.0,-0.990099,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
30,1,DZA,Algeria,1954,0,3.500000,0,0,0.0,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
31,1,DZA,Algeria,1955,0,3.500000,0,0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
32,1,DZA,Algeria,1956,0,3.500000,0,0,0.0,1.980198,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
33,1,DZA,Algeria,1957,0,4.199000,0,0,0.0,2.912621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
34,1,DZA,Algeria,1958,0,4.906000,0,0,0.0,12.264151,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
35,1,DZA,Algeria,1959,0,4.909000,0,0,0.0,9.243697,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
36,1,DZA,Algeria,1960,0,4.937060,0,0,0.0,5.384615,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
37,1,DZA,Algeria,1961,0,4.937060,0,0,0.0,2.919708,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
38,1,DZA,Algeria,1968,0,4.937060,0,0,0.0,6.599988,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
39,1,DZA,Algeria,1969,0,4.937060,0,0,0.0,2.626632,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
40,1,DZA,Algeria,1970,0,4.937060,0,0,0.0,3.656321,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
41,1,DZA,Algeria,1971,0,4.644000,0,0,0.0,6.172816,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
42,1,DZA,Algeria,1972,0,4.556000,0,0,0.0,4.734229,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
43,1,DZA,Algeria,1973,0,4.185000,0,0,0.0,8.961135,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
44,1,DZA,Algeria,1974,0,3.997000,0,0,0.0,8.879172,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
45,1,DZA,Algeria,1975,0,4.125000,0,0,0.0,12.098934,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
46,1,DZA,Algeria,1976,0,4.359000,0,0,0.0,17.173519,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
47,1,DZA,Algeria,1977,0,4.035000,0,0,0.0,11.450379,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
48,1,DZA,Algeria,1978,0,3.834500,0,0,0.0,9.668493,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
49,1,DZA,Algeria,1979,0,3.755500,0,0,0.0,14.609578,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [12]:
from sklearn.model_selection import train_test_split

In [18]:
X = df.drop(columns=['systemic_crisis','country_number','country_code','country','gdp_weighted_default','banking_crisis'])
y= df['systemic_crisis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Step 1: Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Step 4: Train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression Accuracy: 0.9952830188679245
Logistic Regression Confusion Matrix:
 [[195   0]
 [  1  16]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       195
           1       1.00      0.94      0.97        17

    accuracy                           1.00       212
   macro avg       1.00      0.97      0.98       212
weighted avg       1.00      1.00      1.00       212

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize a Decision Tree Classifier model
des_tree = DecisionTreeClassifier()

# Train the model using the training data (X_train) and the corresponding target values (y_train)
des_tree.fit(X_train, y_train)

y_pred = des_tree.predict(X_test)

# Model evaluation
print("Decision Tree Classifier Accuracy:", accuracy_score(y_test, y_pred))
print("Decision Tree Classifier Classification Report:\n", classification_report(y_test, y_pred))
print("Decision Tree Classifier Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Decision Tree Classifier Accuracy: 0.9905660377358491
Decision Tree Classifier Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       195
           1       0.89      1.00      0.94        17

    accuracy                           0.99       212
   macro avg       0.95      0.99      0.97       212
weighted avg       0.99      0.99      0.99       212

Decision Tree Classifier Confusion Matrix:
 [[193   2]
 [  0  17]]

In [21]:
# Step 1: Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Step 4: Train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
print("Random Forest Classifier Accuracy:", accuracy_score(y_test, y_pred))
print("Random Forest Classifier Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Random Forest Classifier Classification Report:\n", classification_report(y_test, y_pred))

Random Forest Classifier Accuracy: 0.9952830188679245
Random Forest Classifier Confusion Matrix:
 [[195   0]
 [  1  16]]
Random Forest Classifier Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       195
           1       1.00      0.94      0.97        17

    accuracy                           1.00       212
   macro avg       1.00      0.97      0.98       212
weighted avg       1.00      1.00      1.00       212